/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controler.Controle;
import java.awt.TextField;
import javax.swing.JButton;
import javax.swing.JPanel;
import model.Divisao;
import model.Multiplicacao;
import model.Soma;
import model.Subtracao;

/**
 *
 * @author unifgnishi
 */
public class Janela extends javax.swing.JFrame {

    /**
     * Creates new form Janela
     */
    public Janela() {
        initComponents();
        control = new Controle(this);
    }
    
    private Controle control;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_4 = new javax.swing.JButton();
        bt_6 = new javax.swing.JButton();
        bt_12 = new javax.swing.JButton();
        bt_14 = new javax.swing.JButton();
        bt_17 = new javax.swing.JButton();
        bt_20 = new javax.swing.JButton();
        bt_22 = new javax.swing.JButton();
        bt_som1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        bt_um = new javax.swing.JButton();
        bt_dois = new javax.swing.JButton();
        bt_tres = new javax.swing.JButton();
        bt_quatro = new javax.swing.JButton();
        bt_cinco = new javax.swing.JButton();
        bt_seis = new javax.swing.JButton();
        bt_sete = new javax.swing.JButton();
        bt_oito = new javax.swing.JButton();
        bt_nove = new javax.swing.JButton();
        bt_zero = new javax.swing.JButton();
        bt_can = new javax.swing.JButton();
        bt_res = new javax.swing.JButton();
        bt_div = new javax.swing.JButton();
        bt_mul = new javax.swing.JButton();
        bt_sub = new javax.swing.JButton();
        bt_som = new javax.swing.JButton();
        txt_resultado = new java.awt.TextField();

        bt_4.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        bt_4.setText("3");
        bt_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_4ActionPerformed(evt);
            }
        });

        bt_6.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        bt_6.setText("4");
        bt_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_6ActionPerformed(evt);
            }
        });

        bt_12.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        bt_12.setText("9");
        bt_12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_12ActionPerformed(evt);
            }
        });

        bt_14.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        bt_14.setText("0");
        bt_14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_14ActionPerformed(evt);
            }
        });

        bt_17.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        bt_17.setText("=");
        bt_17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_17ActionPerformed(evt);
            }
        });

        bt_20.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        bt_20.setText("*");
        bt_20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_20ActionPerformed(evt);
            }
        });

        bt_22.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        bt_22.setText("-");
        bt_22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_22ActionPerformed(evt);
            }
        });

        bt_som1.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        bt_som1.setText("+");
        bt_som1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_som1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");

        jPanel3.setBackground(new java.awt.Color(29, 32, 33));
        jPanel3.setToolTipText("");

        bt_um.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        bt_um.setForeground(new java.awt.Color(250, 189, 47));
        bt_um.setText("1");
        bt_um.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(0, 0, 0))); // NOI18N
        bt_um.setBorderPainted(false);
        bt_um.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_umActionPerformed(evt);
            }
        });

        bt_dois.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        bt_dois.setForeground(new java.awt.Color(250, 189, 47));
        bt_dois.setText("2");
        bt_dois.setBorderPainted(false);
        bt_dois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_doisActionPerformed(evt);
            }
        });

        bt_tres.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        bt_tres.setForeground(new java.awt.Color(250, 189, 47));
        bt_tres.setText("3");
        bt_tres.setBorderPainted(false);
        bt_tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tresActionPerformed(evt);
            }
        });

        bt_quatro.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        bt_quatro.setForeground(new java.awt.Color(250, 189, 47));
        bt_quatro.setText("4");
        bt_quatro.setBorderPainted(false);
        bt_quatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_quatroActionPerformed(evt);
            }
        });

        bt_cinco.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        bt_cinco.setForeground(new java.awt.Color(250, 189, 47));
        bt_cinco.setText("5");
        bt_cinco.setBorderPainted(false);
        bt_cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cincoActionPerformed(evt);
            }
        });

        bt_seis.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        bt_seis.setForeground(new java.awt.Color(250, 189, 47));
        bt_seis.setText("6");
        bt_seis.setBorderPainted(false);
        bt_seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_seisActionPerformed(evt);
            }
        });

        bt_sete.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        bt_sete.setForeground(new java.awt.Color(250, 189, 47));
        bt_sete.setText("7");
        bt_sete.setBorderPainted(false);
        bt_sete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_seteActionPerformed(evt);
            }
        });

        bt_oito.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        bt_oito.setForeground(new java.awt.Color(250, 189, 47));
        bt_oito.setText("8");
        bt_oito.setBorderPainted(false);
        bt_oito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_oitoActionPerformed(evt);
            }
        });

        bt_nove.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        bt_nove.setForeground(new java.awt.Color(250, 189, 47));
        bt_nove.setText("9");
        bt_nove.setBorderPainted(false);
        bt_nove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_noveActionPerformed(evt);
            }
        });

        bt_zero.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        bt_zero.setForeground(new java.awt.Color(250, 189, 47));
        bt_zero.setText("0");
        bt_zero.setBorderPainted(false);
        bt_zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_zeroActionPerformed(evt);
            }
        });

        bt_can.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        bt_can.setForeground(new java.awt.Color(251, 73, 54));
        bt_can.setText("C");
        bt_can.setBorderPainted(false);
        bt_can.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_canActionPerformed(evt);
            }
        });

        bt_res.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        bt_res.setForeground(new java.awt.Color(184, 187, 38));
        bt_res.setText("=");
        bt_res.setBorderPainted(false);
        bt_res.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_resActionPerformed(evt);
            }
        });

        bt_div.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        bt_div.setText("/");
        bt_div.setBorderPainted(false);
        bt_div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_divActionPerformed(evt);
            }
        });

        bt_mul.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        bt_mul.setText("*");
        bt_mul.setBorderPainted(false);
        bt_mul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_mulActionPerformed(evt);
            }
        });

        bt_sub.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        bt_sub.setText("-");
        bt_sub.setBorderPainted(false);
        bt_sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_subActionPerformed(evt);
            }
        });

        bt_som.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        bt_som.setText("+");
        bt_som.setBorderPainted(false);
        bt_som.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_somActionPerformed(evt);
            }
        });

        txt_resultado.setBackground(new java.awt.Color(251, 241, 199));
        txt_resultado.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_resultado.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        txt_resultado.setForeground(new java.awt.Color(29, 32, 33));
        txt_resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_resultadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(bt_sete, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_oito, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_nove, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_div, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(bt_quatro, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_seis, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_mul, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(bt_can, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bt_zero, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(bt_um, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bt_dois, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(bt_tres, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bt_sub, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(bt_res, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bt_som, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_sete, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_oito, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_nove, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_div, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_quatro, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_seis, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_mul, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_um, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_dois, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_tres, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_sub, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_zero, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_can, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_res, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_som, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(165, 165, 165))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 376, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_doisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_doisActionPerformed
        // TODO add your handling code here:
        control.concatenaNumeros("2");
    }//GEN-LAST:event_bt_doisActionPerformed

    private void bt_tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tresActionPerformed
        // TODO add your handling code here:
        control.concatenaNumeros("3");
    }//GEN-LAST:event_bt_tresActionPerformed

    private void bt_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_4ActionPerformed

    private void bt_quatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_quatroActionPerformed
        // TODO add your handling code here:
        control.concatenaNumeros("4");
    }//GEN-LAST:event_bt_quatroActionPerformed

    private void bt_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_6ActionPerformed

    private void bt_cincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cincoActionPerformed
        // TODO add your handling code here:
        control.concatenaNumeros("5");
    }//GEN-LAST:event_bt_cincoActionPerformed

    private void bt_seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_seisActionPerformed
        // TODO add your handling code here:
        control.concatenaNumeros("6");
    }//GEN-LAST:event_bt_seisActionPerformed

    private void bt_seteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_seteActionPerformed
        // TODO add your handling code here:
        control.concatenaNumeros("7");
    }//GEN-LAST:event_bt_seteActionPerformed

    private void bt_oitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_oitoActionPerformed
        // TODO add your handling code here:
        control.concatenaNumeros("8");
    }//GEN-LAST:event_bt_oitoActionPerformed

    private void bt_noveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_noveActionPerformed
        // TODO add your handling code here:
        control.concatenaNumeros("9");
    }//GEN-LAST:event_bt_noveActionPerformed

    private void bt_12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_12ActionPerformed

    private void bt_zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_zeroActionPerformed
        // TODO add your handling code here:
        control.concatenaNumeros("0");
    }//GEN-LAST:event_bt_zeroActionPerformed

    private void bt_14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_14ActionPerformed

    private void bt_canActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_canActionPerformed
        // TODO add your handling code here:
        control.limpar();
    }//GEN-LAST:event_bt_canActionPerformed

    private void bt_resActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_resActionPerformed
        // TODO add your handling code here:
        control.calcular();
    }//GEN-LAST:event_bt_resActionPerformed

    private void bt_17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_17ActionPerformed

    private void bt_divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_divActionPerformed
        // TODO add your handling code here:
        control.salvaOperacao(new Divisao());
    }//GEN-LAST:event_bt_divActionPerformed

    private void bt_mulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_mulActionPerformed
        // TODO add your handling code here:
        control.salvaOperacao(new Multiplicacao());
    }//GEN-LAST:event_bt_mulActionPerformed

    private void bt_20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_20ActionPerformed

    private void bt_subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_subActionPerformed
        // TODO add your handling code here:
        control.salvaOperacao(new Subtracao());
    }//GEN-LAST:event_bt_subActionPerformed

    private void bt_22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_22ActionPerformed

    private void bt_somActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_somActionPerformed
        // TODO add your handling code here:
        control.salvaOperacao(new Soma());
    }//GEN-LAST:event_bt_somActionPerformed

    private void txt_resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_resultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_resultadoActionPerformed

    private void bt_som1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_som1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_som1ActionPerformed

    private void bt_umActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_umActionPerformed
        // TODO add your handling code here:
        control.concatenaNumeros("1");
    }//GEN-LAST:event_bt_umActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Janela().setVisible(true);
//            }
//        });
//    }
    
    public Controle getControl() {
        return control;
    }

    public void setControl(Controle control) {
        this.control = control;
    }

    public JButton getBt_can() {
        return bt_can;
    }

    public void setBt_can(JButton bt_can) {
        this.bt_can = bt_can;
    }

    public JButton getBt_cinco() {
        return bt_cinco;
    }

    public void setBt_cinco(JButton bt_cinco) {
        this.bt_cinco = bt_cinco;
    }

    public JButton getBt_div() {
        return bt_div;
    }

    public void setBt_div(JButton bt_div) {
        this.bt_div = bt_div;
    }

    public JButton getBt_dois() {
        return bt_dois;
    }

    public void setBt_dois(JButton bt_dois) {
        this.bt_dois = bt_dois;
    }

    public JButton getBt_mul() {
        return bt_mul;
    }

    public void setBt_mul(JButton bt_mul) {
        this.bt_mul = bt_mul;
    }

    public JButton getBt_nove() {
        return bt_nove;
    }

    public void setBt_nove(JButton bt_nove) {
        this.bt_nove = bt_nove;
    }

    public JButton getBt_oito() {
        return bt_oito;
    }

    public void setBt_oito(JButton bt_oito) {
        this.bt_oito = bt_oito;
    }

    public JButton getBt_quatro() {
        return bt_quatro;
    }

    public void setBt_quatro(JButton bt_quatro) {
        this.bt_quatro = bt_quatro;
    }

    public JButton getBt_res() {
        return bt_res;
    }

    public void setBt_res(JButton bt_res) {
        this.bt_res = bt_res;
    }

    public JButton getBt_seis() {
        return bt_seis;
    }

    public void setBt_seis(JButton bt_seis) {
        this.bt_seis = bt_seis;
    }

    public JButton getBt_sete() {
        return bt_sete;
    }

    public void setBt_sete(JButton bt_sete) {
        this.bt_sete = bt_sete;
    }

    public JButton getBt_som() {
        return bt_som;
    }

    public void setBt_som(JButton bt_som) {
        this.bt_som = bt_som;
    }

    public JButton getBt_som1() {
        return bt_som1;
    }

    public void setBt_som1(JButton bt_som1) {
        this.bt_som1 = bt_som1;
    }

    public JButton getBt_sub() {
        return bt_sub;
    }

    public void setBt_sub(JButton bt_sub) {
        this.bt_sub = bt_sub;
    }

    public JButton getBt_tres() {
        return bt_tres;
    }

    public void setBt_tres(JButton bt_tres) {
        this.bt_tres = bt_tres;
    }

    public JButton getBt_um() {
        return bt_um;
    }

    public void setBt_um(JButton bt_um) {
        this.bt_um = bt_um;
    }

    public JButton getBt_zero() {
        return bt_zero;
    }

    public void setBt_zero(JButton bt_zero) {
        this.bt_zero = bt_zero;
    }

    public JPanel getjPanel3() {
        return jPanel3;
    }

    public void setjPanel3(JPanel jPanel3) {
        this.jPanel3 = jPanel3;
    }

    public TextField getTxt_resultado() {
        return txt_resultado;
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Janela().setVisible(true);
//            }
//        });
//    }
    public void setTxt_resultado(TextField txt_resultado) {
        this.txt_resultado = txt_resultado;
    }    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_12;
    private javax.swing.JButton bt_14;
    private javax.swing.JButton bt_17;
    private javax.swing.JButton bt_20;
    private javax.swing.JButton bt_22;
    private javax.swing.JButton bt_4;
    private javax.swing.JButton bt_6;
    private javax.swing.JButton bt_can;
    private javax.swing.JButton bt_cinco;
    private javax.swing.JButton bt_div;
    private javax.swing.JButton bt_dois;
    private javax.swing.JButton bt_mul;
    private javax.swing.JButton bt_nove;
    private javax.swing.JButton bt_oito;
    private javax.swing.JButton bt_quatro;
    private javax.swing.JButton bt_res;
    private javax.swing.JButton bt_seis;
    private javax.swing.JButton bt_sete;
    private javax.swing.JButton bt_som;
    private javax.swing.JButton bt_som1;
    private javax.swing.JButton bt_sub;
    private javax.swing.JButton bt_tres;
    private javax.swing.JButton bt_um;
    private javax.swing.JButton bt_zero;
    private javax.swing.JPanel jPanel3;
    private java.awt.TextField txt_resultado;
    // End of variables declaration//GEN-END:variables
}
