package View;

import Controler.Controle;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author unifgnishi
 */
public class Janela extends javax.swing.JFrame {

    /**
     * Creates new form Janela
     */
    public Janela() {
        initComponents();
        c = new Controle(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ibl_x = new javax.swing.JLabel();
        ibl_y = new javax.swing.JLabel();
        ibl_total = new javax.swing.JLabel();
        txt_x = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();
        txt_y = new javax.swing.JTextField();
        bt_limpar = new javax.swing.JButton();
        bt_somar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ibl_x.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        ibl_x.setText("Numero 1:");

        ibl_y.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        ibl_y.setText("Numero 2:");

        ibl_total.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        ibl_total.setText("Total:");

        txt_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalActionPerformed(evt);
            }
        });

        txt_y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_yActionPerformed(evt);
            }
        });

        bt_limpar.setText("Limpar");
        bt_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_limparActionPerformed(evt);
            }
        });

        bt_somar.setText("Somar");
        bt_somar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_somarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ibl_y)
                            .addComponent(ibl_x)
                            .addComponent(ibl_total, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bt_somar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_limpar)
                    .addComponent(txt_y, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_x, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ibl_x)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txt_x, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ibl_y)
                    .addComponent(txt_y))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ibl_total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_total))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_limpar)
                    .addComponent(bt_somar))
                .addGap(75, 75, 75))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalActionPerformed

    private void txt_yActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_yActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_yActionPerformed

    private void bt_somarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_somarActionPerformed
        // TODO add your handling code here:
        c.controleSomar();
    }//GEN-LAST:event_bt_somarActionPerformed

    private void bt_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_limparActionPerformed
        // TODO add your handling code here:
        c.controleLimpar();
    }//GEN-LAST:event_bt_limparActionPerformed

    /**
     * @param args the command line arguments
     * @return 
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Janela().setVisible(true);
//            }
//        });
//    }

    public JButton getBt_limpar() {
        return bt_limpar;
    }

    public void setBt_limpar(JButton bt_limpar) {
        this.bt_limpar = bt_limpar;
    }

    public JButton getBt_somar() {
        return bt_somar;
    }

    public void setBt_somar(JButton bt_somar) {
        this.bt_somar = bt_somar;
    }

    public JLabel getIbl_total() {
        return ibl_total;
    }

    public void setIbl_total(JLabel ibl_total) {
        this.ibl_total = ibl_total;
    }

    public JLabel getIbl_x() {
        return ibl_x;
    }

    public void setIbl_x(JLabel ibl_x) {
        this.ibl_x = ibl_x;
    }

    public JLabel getIbl_y() {
        return ibl_y;
    }

    public void setIbl_y(JLabel ibl_y) {
        this.ibl_y = ibl_y;
    }

    public JTextField getTxt_total() {
        return txt_total;
    }

    public void setTxt_total(JTextField txt_total) {
        this.txt_total = txt_total;
    }

    public JTextField getTxt_x() {
        return txt_x;
    }

    public void setTxt_x(JTextField txt_x) {
        this.txt_x = txt_x;
    }

    public JTextField getTxt_y() {
        return txt_y;
    }

    public void setTxt_y(JTextField txt_y) {
        this.txt_y = txt_y;
    }

    private final Controle c;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_limpar;
    private javax.swing.JButton bt_somar;
    private javax.swing.JLabel ibl_total;
    private javax.swing.JLabel ibl_x;
    private javax.swing.JLabel ibl_y;
    private javax.swing.JTextField txt_total;
    private javax.swing.JTextField txt_x;
    private javax.swing.JTextField txt_y;
    // End of variables declaration//GEN-END:variables
}
