/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.Controle;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author unifgnishi
 */
public class JanelaPricipal extends javax.swing.JFrame {

    /**
     * Creates new form JanelaPricipal
     */
    public JanelaPricipal() {
        initComponents();
        Controle control = new Controle(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ibl_cpf = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        txt_sobrenome = new javax.swing.JTextField();
        txt_idade = new javax.swing.JTextField();
        txt_cpf = new javax.swing.JTextField();
        ibl_nome = new javax.swing.JLabel();
        ibl_sobrenome = new javax.swing.JLabel();
        ibl_idade = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ibl_genero = new javax.swing.JLabel();
        btn_masculino = new javax.swing.JRadioButton();
        btn_feminino = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ibl_cpf.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        ibl_cpf.setText("CPF:");

        txt_nome.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        txt_sobrenome.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        txt_idade.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        txt_cpf.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        ibl_nome.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        ibl_nome.setText("Nome:");

        ibl_sobrenome.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        ibl_sobrenome.setText("Sobrenome:");

        ibl_idade.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        ibl_idade.setText("Idade:");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        ibl_genero.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        ibl_genero.setText("Gênero:");

        btn_masculino.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        btn_masculino.setText("Masculino");
        btn_masculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_masculinoActionPerformed(evt);
            }
        });

        btn_feminino.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        btn_feminino.setText("Feminino");
        btn_feminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_femininoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_masculino)
                    .addComponent(ibl_genero)
                    .addComponent(btn_feminino))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ibl_genero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_masculino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_feminino)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jButton1.setText("Cadastrar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ibl_cpf)
                            .addComponent(ibl_idade)
                            .addComponent(ibl_sobrenome)
                            .addComponent(ibl_nome))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_sobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_idade, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jButton1)))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ibl_nome)
                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ibl_sobrenome)
                    .addComponent(txt_sobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ibl_idade)
                    .addComponent(txt_idade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ibl_cpf)
                    .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(158, 158, 158))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_masculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_masculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_masculinoActionPerformed

    private void btn_femininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_femininoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_femininoActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JanelaPricipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JanelaPricipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JanelaPricipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JanelaPricipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new JanelaPricipal().setVisible(true);
//            }
//        });
//    }

    public JRadioButton getBtn_feminino() {
        return btn_feminino;
    }

    public void setBtn_feminino(JRadioButton btn_feminino) {
        this.btn_feminino = btn_feminino;
    }

    public JRadioButton getBtn_masculino() {
        return btn_masculino;
    }

    public void setBtn_masculino(JRadioButton btn_masculino) {
        this.btn_masculino = btn_masculino;
    }

    public JLabel getIbl_cpf() {
        return ibl_cpf;
    }

    public void setIbl_cpf(JLabel ibl_cpf) {
        this.ibl_cpf = ibl_cpf;
    }

    public JLabel getIbl_genero() {
        return ibl_genero;
    }

    public void setIbl_genero(JLabel ibl_genero) {
        this.ibl_genero = ibl_genero;
    }

    public JLabel getIbl_idade() {
        return ibl_idade;
    }

    public void setIbl_idade(JLabel ibl_idade) {
        this.ibl_idade = ibl_idade;
    }

    public JLabel getIbl_nome() {
        return ibl_nome;
    }

    public void setIbl_nome(JLabel ibl_nome) {
        this.ibl_nome = ibl_nome;
    }

    public JLabel getIbl_sobrenome() {
        return ibl_sobrenome;
    }

    public void setIbl_sobrenome(JLabel ibl_sobrenome) {
        this.ibl_sobrenome = ibl_sobrenome;
    }

    public JButton getjButton1() {
        return jButton1;
    }

    public void setjButton1(JButton jButton1) {
        this.jButton1 = jButton1;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JTextField getTxt_cpf() {
        return txt_cpf;
    }

    public void setTxt_cpf(JTextField txt_cpf) {
        this.txt_cpf = txt_cpf;
    }

    public JTextField getTxt_idade() {
        return txt_idade;
    }

    public void setTxt_idade(JTextField txt_idade) {
        this.txt_idade = txt_idade;
    }

    public JTextField getTxt_nome() {
        return txt_nome;
    }

    public void setTxt_nome(JTextField txt_nome) {
        this.txt_nome = txt_nome;
    }

    public JTextField getTxt_sobrenome() {
        return txt_sobrenome;
    }
    
    public void setTxt_sobrenome(JTextField txt_sobrenome) {
        this.txt_sobrenome = txt_sobrenome;
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JanelaPricipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JanelaPricipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JanelaPricipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JanelaPricipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new JanelaPricipal().setVisible(true);
//            }
//        });
    //    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btn_feminino;
    private javax.swing.JRadioButton btn_masculino;
    private javax.swing.JLabel ibl_cpf;
    private javax.swing.JLabel ibl_genero;
    private javax.swing.JLabel ibl_idade;
    private javax.swing.JLabel ibl_nome;
    private javax.swing.JLabel ibl_sobrenome;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_cpf;
    private javax.swing.JTextField txt_idade;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_sobrenome;
    // End of variables declaration//GEN-END:variables


   
}
